language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_EMULATOR_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
    - QEMU_AUDIO_DRV=none

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - android list targets
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - mkdir -p build/reports
  - ./gradlew assembleDebugAndroidTest -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - ./gradlew connectedDebugAndroidTest -PdisablePreDex --continue --stacktrace

branches:
  - master
  - devel

after_failure:
  - cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml