language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.1
  - android-28
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - "ls"
skip_cleanup: true
branches:
  - master
  - devel
before_install:
  - chmod +x gradlew
  - chmod +rx app